name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs: 
  Explore-GitHub-Actions:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ci-example
    steps:
      - name: Setup LTS Version of NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install all Dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint
      - name: Run Unit Tests
        run: npm run test
      - name: Build App
        run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: AWS Bucket Access
        env: 
          AWS_BUCKET_NAME: cibucket2024
        run: aws s3 sync build  s3://${{ AWS_BUCKET_NAME }}
